2018-05-29 08:38:29,702 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-29 08:40:18,992 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-29 08:51:34,911 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-29 08:53:08,703 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-29 08:53:50,699 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-29 08:54:27,295 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-29 08:54:45,469 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-29 09:13:32,579 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-29 09:14:12,144 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-29 09:14:46,035 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-29 09:16:14,739 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-29 09:18:11,303 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-29 09:19:39,039 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-29 09:33:21,484 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-29 09:34:30,111 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-29 09:35:40,986 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-29 09:36:11,506 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-06-26 21:24:10,456 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-06-26 21:26:13,883 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-06-26 21:28:01,632 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-06-26 21:28:05,997 ERROR: Exception on /static/auth.css [GET] [in /home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/helpers.py", line 976, in send_static_file
    cache_timeout=cache_timeout)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/helpers.py", line 709, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 1713, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 1644, in handle_http_exception
    return handler(e)
  File "/home/salesvictor/PyTube/app/errors.py", line 13, in generic_error
    return render_template('error.html', error=code, desc=desc), code
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/salesvictor/PyTube/app/templates/error.html", line 9, in top-level template code
    <link rel="stylesheet" href="{{ url_for('static/css', filename='error.css') }}">
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'static/css' with values ['filename']. Did you mean 'static' instead?
2018-06-26 21:28:05,999 ERROR: Exception on /static/logo.png [GET] [in /home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/helpers.py", line 976, in send_static_file
    cache_timeout=cache_timeout)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/helpers.py", line 709, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 1713, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 1644, in handle_http_exception
    return handler(e)
  File "/home/salesvictor/PyTube/app/errors.py", line 13, in generic_error
    return render_template('error.html', error=code, desc=desc), code
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/salesvictor/PyTube/app/templates/error.html", line 9, in top-level template code
    <link rel="stylesheet" href="{{ url_for('static/css', filename='error.css') }}">
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'static/css' with values ['filename']. Did you mean 'static' instead?
2018-06-26 21:28:13,226 ERROR: Exception on /static/error.html [GET] [in /home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/helpers.py", line 976, in send_static_file
    cache_timeout=cache_timeout)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/helpers.py", line 709, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 1713, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 1644, in handle_http_exception
    return handler(e)
  File "/home/salesvictor/PyTube/app/errors.py", line 13, in generic_error
    return render_template('error.html', error=code, desc=desc), code
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/salesvictor/PyTube/app/templates/error.html", line 9, in top-level template code
    <link rel="stylesheet" href="{{ url_for('static/css', filename='error.css') }}">
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'static/css' with values ['filename']. Did you mean 'static' instead?
2018-06-26 21:28:55,892 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-06-26 21:29:42,445 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-06-26 22:10:44,500 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-06-26 22:28:20,406 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-06-26 22:29:15,234 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-06-26 22:31:26,205 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
