2018-05-28 09:38:10,334 ERROR: Exception on /user_profile [GET] [in /home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/salesvictor/PyTube/app/routes.py", line 11, in user_profile
    return render_template('user_profile.html')
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: user_profile.html
2018-05-28 09:39:48,980 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-28 09:39:53,270 ERROR: Exception on /user_profile [GET] [in /home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/salesvictor/PyTube/app/routes.py", line 11, in user_profile
    return render_template('user_profile.html')
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: user_profile.html
2018-05-28 09:49:01,692 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-28 09:51:50,277 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-28 09:51:57,412 ERROR: Exception on /user_profile [GET] [in /home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/salesvictor/PyTube/app/routes.py", line 11, in user_profile
    return render_template('user_profile.html')
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: user_profile.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 1719, in handle_user_exception
    return handler(e)
  File "/home/salesvictor/PyTube/app/errors.py", line 11, in generic_error
    if isinstance(error, HTTPException):
NameError: name 'HTTPException' is not defined
2018-05-28 09:52:28,994 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-28 09:52:32,466 ERROR: Exception on /user_profile [GET] [in /home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/salesvictor/PyTube/app/routes.py", line 11, in user_profile
    return render_template('user_profile.html')
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: user_profile.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/salesvictor/.local/share/virtualenvs/PyTube-ZcennWwD/lib/python3.6/site-packages/flask/app.py", line 1719, in handle_user_exception
    return handler(e)
  File "/home/salesvictor/PyTube/app/errors.py", line 14, in generic_error
    return render_template('error.html', error=error), HTTPExceptionde
NameError: name 'HTTPExceptionde' is not defined
2018-05-28 09:52:38,872 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-28 09:52:49,406 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-28 09:53:16,917 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-28 10:07:10,100 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-28 10:11:05,921 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-28 10:13:47,035 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-28 10:14:21,591 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-28 10:15:16,716 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-28 10:16:23,274 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-28 10:16:45,788 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-28 10:18:08,437 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-28 10:18:29,906 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-28 10:19:00,227 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-28 10:20:02,230 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-28 10:20:19,050 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-28 10:21:32,551 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-28 10:23:09,276 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-28 10:23:24,005 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
2018-05-28 10:25:09,363 INFO: PyTube Startup [in /home/salesvictor/PyTube/app/__init__.py:33]
